# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YemeksepetiProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YemeksepetiProject

  pod 'Alamofire'

  pod 'AlamofireImage'

  pod 'Firebase'
 
  pod 'Firebase/Auth'	

  target 'YemeksepetiProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YemeksepetiProjectUITests' do
    # Pods for testing
  end

end
